---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
#words: I,You,He,She,It
words: Jack,Kim,Bill,Trump,Lee2
   
---
spring:
  profiles: verb
words: killed,slashed,attacked,saw,kicked

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: US,North Korea,vote,seat,tissue,floor,dog
  
